# Generated by Django 5.2.6 on 2025-10-30 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EvalMateApp', '0003_alter_formresponse_options_and_more'),
    ]

    operations = [
        # Add indexes to Profile model
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['account_type', 'institution'], name='EvalMateApp_account_idx'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='account_type',
            field=models.CharField(choices=[('student', 'Student'), ('faculty', 'Faculty')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='institution',
            field=models.CharField(db_index=True, max_length=100),
        ),
        
        # Add indexes to FormTemplate model
        migrations.AlterModelOptions(
            name='formtemplate',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(
            model_name='formtemplate',
            index=models.Index(fields=['institution', 'privacy'], name='EvalMateApp_institu_idx'),
        ),
        migrations.AddIndex(
            model_name='formtemplate',
            index=models.Index(fields=['created_by', '-created_at'], name='EvalMateApp_created_idx'),
        ),
        migrations.AlterField(
            model_name='formtemplate',
            name='title',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='formtemplate',
            name='course_id',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='formtemplate',
            name='institution',
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='formtemplate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        
        # Add indexes to FormResponse model
        migrations.AlterModelOptions(
            name='formresponse',
            options={'ordering': ['-submitted_at']},
        ),
        migrations.AddIndex(
            model_name='formresponse',
            index=models.Index(fields=['form', '-submitted_at'], name='EvalMateApp_form_idx'),
        ),
        migrations.AddIndex(
            model_name='formresponse',
            index=models.Index(fields=['is_read', 'form'], name='EvalMateApp_is_read_idx'),
        ),
        migrations.AlterField(
            model_name='formresponse',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='formresponse',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
