# Generated by Django 5.2.6 on 2025-10-31 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EvalMateApp', '0003_profile_email_verified_profile_verification_code_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE \"EvalMateApp_profile\" DROP COLUMN IF EXISTS \"course\" CASCADE;",
            reverse_sql="ALTER TABLE \"EvalMateApp_profile\" ADD COLUMN \"course\" VARCHAR(100);"
        ),
    ]
