# Generated by Django 5.2.6 on 2025-10-31 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EvalMateApp', '0004_auto_20251030_1302'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='formresponse',
            name='EvalMateApp_form_idx',
        ),
        migrations.RemoveIndex(
            model_name='formresponse',
            name='EvalMateApp_is_read_idx',
        ),
        migrations.RemoveIndex(
            model_name='formtemplate',
            name='EvalMateApp_institu_idx',
        ),
        migrations.RemoveIndex(
            model_name='formtemplate',
            name='EvalMateApp_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='profile',
            name='EvalMateApp_account_idx',
        ),
        migrations.AlterField(
            model_name='formtemplate',
            name='privacy',
            field=models.CharField(choices=[('private', 'Draft (Not Published)'), ('institution', 'Same Institution'), ('institution_course', 'Same Institution and Course')], default='private', max_length=30),
        ),
    ]
