# Generated by Django 5.2.6 on 2025-11-01 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EvalMateApp', '0005_add_private_draft_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='formresponse',
            name='team_identifier',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='formresponse',
            name='teammate_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='formresponse',
            index=models.Index(fields=['team_identifier'], name='EvalMateApp_team_id_37f60f_idx'),
        ),
    ]
