# Generated by Django 5.2.6 on 2025-11-02 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EvalMateApp', '0006_formresponse_team_identifier_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_students', to='EvalMateApp.formtemplate')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_evaluations', to='EvalMateApp.profile')),
            ],
            options={
                'ordering': ['-added_at'],
                'indexes': [models.Index(fields=['student', '-added_at'], name='EvalMateApp_student_ef697f_idx')],
                'unique_together': {('student', 'form')},
            },
        ),
    ]
