# Generated by Django 5.2.6 on 2025-11-02 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EvalMateApp', '0007_pendingevaluation'),
    ]

    operations = [
        migrations.CreateModel(
            name='DraftResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draft_data', models.JSONField(default=dict)),
                ('team_identifier', models.CharField(blank=True, max_length=255, null=True)),
                ('teammate_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_saved', models.DateTimeField(auto_now=True, db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_responses', to='EvalMateApp.formtemplate')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_responses', to='EvalMateApp.profile')),
            ],
            options={
                'ordering': ['-last_saved'],
                'indexes': [models.Index(fields=['student', '-last_saved'], name='EvalMateApp_student_905d66_idx')],
                'unique_together': {('student', 'form', 'team_identifier', 'teammate_name')},
            },
        ),
    ]
