# Generated by Django 5.2.6 on 2025-11-03 03:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EvalMateApp', '0009_fix_formresponse_fk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formresponse',
            options={'ordering': ['-submitted_at']},
        ),
        migrations.AlterModelOptions(
            name='formtemplate',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='formresponse',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='formresponse',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='formresponse',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='formresponse',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='formtemplate',
            name='course_id',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='formtemplate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='formtemplate',
            name='institution',
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='formtemplate',
            name='title',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='account_type',
            field=models.CharField(choices=[('student', 'Student'), ('faculty', 'Faculty')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='institution',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='formresponse',
            index=models.Index(fields=['form', '-submitted_at'], name='EvalMateApp_form_id_c801e3_idx'),
        ),
        migrations.AddIndex(
            model_name='formresponse',
            index=models.Index(fields=['is_read', 'form'], name='EvalMateApp_is_read_3ac71c_idx'),
        ),
        migrations.AddIndex(
            model_name='formtemplate',
            index=models.Index(fields=['institution', 'privacy'], name='EvalMateApp_institu_7ab2e9_idx'),
        ),
        migrations.AddIndex(
            model_name='formtemplate',
            index=models.Index(fields=['created_by', '-created_at'], name='EvalMateApp_created_1453db_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['account_type', 'institution'], name='EvalMateApp_account_abf2dc_idx'),
        ),
    ]
