# Generated by Django 5.2.6 on 2025-11-24 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EvalMateApp', '0010_alter_formresponse_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email_verified',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='verification_code',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='verification_code_created',
        ),
    ]
