# Generated by Django 5.2.6 on 2025-12-02 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EvalMateApp', '0012_add_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formresponse',
            name='is_draft',
        ),
        migrations.DeleteModel(
            name='DraftResponse',
        ),
    ]
