# Generated by Django 5.2.6 on 2025-12-02 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EvalMateApp', '0013_remove_draft_functionality'),
        ('EvalMateApp', '0014_add_profile_picture_url'),
    ]

    operations = [
    ]
