"""
Script to manually create the missing FormTemplate table in Supabase
Run this with: python manage.py shell < create_formtemplate_table.py
"""

from django.db import connection

sql = """
CREATE TABLE IF NOT EXISTS "EvalMateApp_formtemplate" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "title" varchar(200) NOT NULL,
    "description" text NOT NULL,
    "course_id" varchar(50) NOT NULL,
    "institution" varchar(200) NOT NULL,
    "structure" jsonb NOT NULL,
    "created_at" timestamp with time zone NOT NULL,
    "privacy" varchar(30) NOT NULL,
    "passcode" varchar(50),
    "created_by_id" bigint NOT NULL,
    CONSTRAINT "EvalMateApp_formte_created_by_id_d2831afc_fk_EvalMateA" 
        FOREIGN KEY ("created_by_id") 
        REFERENCES "EvalMateApp_profile" ("id") 
        DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX IF NOT EXISTS "EvalMateApp_formtemplate_created_by_id_d2831afc" 
    ON "EvalMateApp_formtemplate" ("created_by_id");
"""

with connection.cursor() as cursor:
    cursor.execute(sql)
    
print("✅ FormTemplate table created successfully!")
print("You can now publish forms from the Form Builder.")
