from django.core.management.base import BaseCommand
from django.db import connection


class Command(BaseCommand):
    help = 'Ensures all EvalMate tables have the correct structure in Supabase'

    def handle(self, *args, **options):
        
        # Create ResponseAnswer table if it doesn't exist
        self.stdout.write('Creating/verifying ResponseAnswer table...')
        sql_responseanswer = """
        CREATE TABLE IF NOT EXISTS "EvalMateApp_responseanswer" (
            "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
            "question" text NOT NULL,
            "answer" text NOT NULL,
            "response_id" bigint NOT NULL,
            CONSTRAINT "EvalMateApp_respon_response_id_c8d1e829_fk_EvalMateA"
                FOREIGN KEY ("response_id")
                REFERENCES "EvalMateApp_formresponse" ("id")
                DEFERRABLE INITIALLY DEFERRED
        );

        CREATE INDEX IF NOT EXISTS "EvalMateApp_responseanswer_response_id_c8d1e829"
            ON "EvalMateApp_responseanswer" ("response_id");
        """
        
        # Ensure all FormResponse columns exist
        self.stdout.write('Verifying FormResponse columns...')
        sql_formresponse_columns = """
        ALTER TABLE "EvalMateApp_formresponse"
        ADD COLUMN IF NOT EXISTS "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY;
        
        ALTER TABLE "EvalMateApp_formresponse"
        ADD COLUMN IF NOT EXISTS "submitted_at" timestamp with time zone NOT NULL DEFAULT NOW();
        
        ALTER TABLE "EvalMateApp_formresponse"
        ADD COLUMN IF NOT EXISTS "is_read" boolean NOT NULL DEFAULT false;
        
        ALTER TABLE "EvalMateApp_formresponse"
        ADD COLUMN IF NOT EXISTS "form_id" bigint NOT NULL;
        
        ALTER TABLE "EvalMateApp_formresponse"
        ADD COLUMN IF NOT EXISTS "submitted_by_id" bigint;
        """
        
        # Ensure all FormTemplate columns exist
        self.stdout.write('Verifying FormTemplate columns...')
        sql_formtemplate_columns = """
        ALTER TABLE "EvalMateApp_formtemplate"
        ADD COLUMN IF NOT EXISTS "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY;
        
        ALTER TABLE "EvalMateApp_formtemplate"
        ADD COLUMN IF NOT EXISTS "title" varchar(200) NOT NULL DEFAULT '';
        
        ALTER TABLE "EvalMateApp_formtemplate"
        ADD COLUMN IF NOT EXISTS "description" text NOT NULL DEFAULT '';
        
        ALTER TABLE "EvalMateApp_formtemplate"
        ADD COLUMN IF NOT EXISTS "course_id" varchar(50) NOT NULL DEFAULT '';
        
        ALTER TABLE "EvalMateApp_formtemplate"
        ADD COLUMN IF NOT EXISTS "institution" varchar(200) NOT NULL DEFAULT '';
        
        ALTER TABLE "EvalMateApp_formtemplate"
        ADD COLUMN IF NOT EXISTS "structure" jsonb NOT NULL DEFAULT '{}'::jsonb;
        
        ALTER TABLE "EvalMateApp_formtemplate"
        ADD COLUMN IF NOT EXISTS "created_at" timestamp with time zone NOT NULL DEFAULT NOW();
        
        ALTER TABLE "EvalMateApp_formtemplate"
        ADD COLUMN IF NOT EXISTS "privacy" varchar(30) NOT NULL DEFAULT 'institution';
        
        ALTER TABLE "EvalMateApp_formtemplate"
        ADD COLUMN IF NOT EXISTS "passcode" varchar(50);
        
        ALTER TABLE "EvalMateApp_formtemplate"
        ADD COLUMN IF NOT EXISTS "created_by_id" bigint NOT NULL;
        """
        
        # Ensure Profile table columns
        self.stdout.write('Verifying Profile columns...')
        sql_profile_columns = """
        ALTER TABLE "EvalMateApp_profile"
        ADD COLUMN IF NOT EXISTS "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY;
        
        ALTER TABLE "EvalMateApp_profile"
        ADD COLUMN IF NOT EXISTS "account_type" varchar(10) NOT NULL DEFAULT 'student';
        
        ALTER TABLE "EvalMateApp_profile"
        ADD COLUMN IF NOT EXISTS "first_name" varchar(30) NOT NULL DEFAULT '';
        
        ALTER TABLE "EvalMateApp_profile"
        ADD COLUMN IF NOT EXISTS "last_name" varchar(30) NOT NULL DEFAULT '';
        
        ALTER TABLE "EvalMateApp_profile"
        ADD COLUMN IF NOT EXISTS "email" varchar(254) NOT NULL DEFAULT '';
        
        ALTER TABLE "EvalMateApp_profile"
        ADD COLUMN IF NOT EXISTS "student_id" varchar(20) NOT NULL DEFAULT '';
        
        ALTER TABLE "EvalMateApp_profile"
        ADD COLUMN IF NOT EXISTS "phone_number" varchar(15) NOT NULL DEFAULT '';
        
        ALTER TABLE "EvalMateApp_profile"
        ADD COLUMN IF NOT EXISTS "institution" varchar(100) NOT NULL DEFAULT '';
        
        ALTER TABLE "EvalMateApp_profile"
        ADD COLUMN IF NOT EXISTS "department" varchar(100) NOT NULL DEFAULT '';
        
        ALTER TABLE "EvalMateApp_profile"
        ADD COLUMN IF NOT EXISTS "user_id" bigint NOT NULL;
        """

        with connection.cursor() as cursor:
            try:
                cursor.execute(sql_responseanswer)
                self.stdout.write(self.style.SUCCESS('  ✅ ResponseAnswer table ready'))
            except Exception as e:
                self.stdout.write(self.style.WARNING(f'  ⚠ ResponseAnswer: {e}'))
            
            try:
                cursor.execute(sql_formresponse_columns)
                self.stdout.write(self.style.SUCCESS('  ✅ FormResponse columns verified'))
            except Exception as e:
                self.stdout.write(self.style.WARNING(f'  ⚠ FormResponse: {e}'))
            
            try:
                cursor.execute(sql_formtemplate_columns)
                self.stdout.write(self.style.SUCCESS('  ✅ FormTemplate columns verified'))
            except Exception as e:
                self.stdout.write(self.style.WARNING(f'  ⚠ FormTemplate: {e}'))
            
            try:
                cursor.execute(sql_profile_columns)
                self.stdout.write(self.style.SUCCESS('  ✅ Profile columns verified'))
            except Exception as e:
                self.stdout.write(self.style.WARNING(f'  ⚠ Profile: {e}'))
        
        self.stdout.write('')
        self.stdout.write(self.style.SUCCESS('=' * 60))
        self.stdout.write(self.style.SUCCESS('✅ Database structure verified and updated!'))
        self.stdout.write(self.style.SUCCESS('=' * 60))
        self.stdout.write('')
        self.stdout.write('Next steps:')
        self.stdout.write('1. Restart your Django server')
        self.stdout.write('2. Test student form search')
        self.stdout.write('3. Test form submission to Supabase')
